name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      
    - name: Build Docker image
      run: docker build -t ${{ secrets.aayansheikh }}/expense-predictor:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.aayansheikh }}/expense-predictor:latest
